version: "3.8"

services:
  pg:
    container_name: postgres-prisma-test
    image: postgres:13
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: askconsult
# volumes:
#   db:
#     driver: local
